/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GeneratedBadgeProps {
  size?: 's' | 'xs';
  shape?: 'square' | 'rounded' | 'circular';
  state?: 'default' | 'disabled';
  appearance?:
    | 'tracker-solid-neutral'
    | 'tracker-solid-positive'
    | 'tracker-solid-attention'
    | 'primary-solid'
    | 'primary-solid-alt'
    | 'primary-transparent'
    | 'secondary-solid'
    | 'secondary-solid-alt'
    | 'secondary-transparent'
    | 'tertiary-solid'
    | 'tertiary-transparent'
    | 'primary'
    | 'secondary'
    | 'tertiary'
    | 'quaternary'
    | 'informative'
    | 'positive'
    | 'attention'
    | 'negative';
}
