/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GeneratedTextareaProps {
  size?: '2xl' | 'xl' | 'l' | 'm' | 's' | 'xs';
  shape?: 'circular' | 'rounded';
  state?: 'pending' | 'success' | 'warning' | 'error';
  appearance?: 'light' | 'lightest';
  variant?: 'solid' | 'solid-outline' | 'elevate' | 'ghost-outline';
}
