enableScripts: true

nodeLinker: node-modules

npmScopes:
  d-sys-team:
    npmAlwaysAuth: true
    npmAuthToken: Yn6TH9DyT87zMPUdhxJS
    npmRegistryServer: "https://gitlab.com/api/v4/projects/50873891/packages/npm/"  
  kit-base:
    npmAlwaysAuth: true
    npmAuthToken: Yn6TH9DyT87zMPUdhxJS
    npmRegistryServer: "https://gitlab.com/api/v4/projects/50873891/packages/npm/"  
  kit-xyz:
    npmAlwaysAuth: true
    npmAuthToken: Yn6TH9DyT87zMPUdhxJS
    npmRegistryServer: "https://gitlab.com/api/v4/projects/50873891/packages/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
