/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GeneratedBubbleProps {
  size?: '2xl' | 'xl' | 'l' | 'm' | 's' | 'xs';
  shape?: 'corner' | 'circular' | 'rounded';
  appearance?: 'dark' | 'light' | 'primary';
  variant?: 'solid' | 'elevate';
}
