/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GeneratedButtonProps {
  size?: 's' | 'xs';
  shape?: 'circular' | 'rounded' | 'square';
  state?: 'default' | 'success' | 'loading' | 'error';
  appearance?:
    | 'tracker-solid-primary'
    | 'tracker-transparent-primary'
    | 'tracker-transparent-secondary'
    | 'primary-solid'
    | 'primary-solid-alt'
    | 'primary-transparent'
    | 'secondary-solid'
    | 'secondary-solid-alt'
    | 'secondary-transparent'
    | 'tertiary-solid'
    | 'tertiary-transparent'
    | 'quaternary-solid';
}
