/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GeneratedInputProps {
  size?: 's';
  shape?: 'square' | 'rounded' | 'circular';
  state?: 'success' | 'error';
  appearance?:
    | 'primary-solid'
    | 'primary-transparent'
    | 'secondary-solid'
    | 'secondary-transparent'
    | 'tertiary-solid'
    | 'tertiary-transparent';
}
