export const FONTS = {
  sans: {
    '8xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '500',
          lineHeight: '192px',
          fontSize: '220px',
          letterSpacing: '-8%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '200',
          lineHeight: '192px',
          fontSize: '220px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '7xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '500',
          lineHeight: '96px',
          fontSize: '110px',
          letterSpacing: '-6%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '200',
          lineHeight: '96px',
          fontSize: '110px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '6xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '500',
          lineHeight: '72px',
          fontSize: '88px',
          letterSpacing: '-6%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '200',
          lineHeight: '72px',
          fontSize: '88px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '5xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '500',
          lineHeight: '56px',
          fontSize: '66px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '200',
          lineHeight: '56px',
          fontSize: '66px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '4xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '500',
          lineHeight: '48px',
          fontSize: '55px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '200',
          lineHeight: '48px',
          fontSize: '55px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '3xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '500',
          lineHeight: '40px',
          fontSize: '44px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '200',
          lineHeight: '40px',
          fontSize: '44px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '2xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '500',
          lineHeight: '32px',
          fontSize: '33px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '200',
          lineHeight: '32px',
          fontSize: '33px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    xl: {
      bold: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '500',
          lineHeight: '24px',
          fontSize: '22px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '300',
          lineHeight: '24px',
          fontSize: '22px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      'regular-underline': {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '300',
          lineHeight: '24px',
          fontSize: '22px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'underline',
        },
        type: 'typography',
      },
      'regular-strikethrough': {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '300',
          lineHeight: '24px',
          fontSize: '22px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'line-through',
        },
        type: 'typography',
      },
    },
    l: {
      bold: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '500',
          lineHeight: '20px',
          fontSize: '16px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '300',
          lineHeight: '20px',
          fontSize: '16px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      'regular-underline': {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '300',
          lineHeight: '20px',
          fontSize: '16px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'underline',
        },
        type: 'typography',
      },
      'regular-strikethrough': {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '300',
          lineHeight: '20px',
          fontSize: '16px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'line-through',
        },
        type: 'typography',
      },
    },
    m: {
      bold: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '500',
          lineHeight: '16px',
          fontSize: '14px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '400',
          lineHeight: '16px',
          fontSize: '14px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      'regular-underline': {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '400',
          lineHeight: '16px',
          fontSize: '14px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'underline',
        },
        type: 'typography',
      },
      'regular-strikethrough': {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '400',
          lineHeight: '16px',
          fontSize: '14px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'line-through',
        },
        type: 'typography',
      },
    },
    s: {
      bold: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '500',
          lineHeight: '14px',
          fontSize: '11px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '400',
          lineHeight: '14px',
          fontSize: '11px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      'regular-underline': {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '400',
          lineHeight: '14px',
          fontSize: '11px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'underline',
        },
        type: 'typography',
      },
      'regular-strikethrough': {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '400',
          lineHeight: '14px',
          fontSize: '11px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'line-through',
        },
        type: 'typography',
      },
    },
    xs: {
      bold: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '500',
          lineHeight: '12px',
          fontSize: '8px',
          letterSpacing: '-2%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '400',
          lineHeight: '12px',
          fontSize: '8px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      'regular-underline': {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '400',
          lineHeight: '12px',
          fontSize: '8px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'underline',
        },
        type: 'typography',
      },
      'regular-strikethrough': {
        value: {
          fontFamily: 'SB Sans Text',
          fontWeight: '400',
          lineHeight: '12px',
          fontSize: '8px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'line-through',
        },
        type: 'typography',
      },
    },
  },
  serif: {
    '8xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '500',
          lineHeight: '192px',
          fontSize: '220px',
          letterSpacing: '-8%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '200',
          lineHeight: '192px',
          fontSize: '220px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '7xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '500',
          lineHeight: '96px',
          fontSize: '110px',
          letterSpacing: '-6%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '200',
          lineHeight: '96px',
          fontSize: '110px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '6xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '500',
          lineHeight: '72px',
          fontSize: '88px',
          letterSpacing: '-6%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '200',
          lineHeight: '72px',
          fontSize: '88px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '5xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '500',
          lineHeight: '56px',
          fontSize: '66px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '200',
          lineHeight: '56px',
          fontSize: '66px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '4xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '500',
          lineHeight: '48px',
          fontSize: '55px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '200',
          lineHeight: '48px',
          fontSize: '55px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '3xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '500',
          lineHeight: '40px',
          fontSize: '44px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '200',
          lineHeight: '40px',
          fontSize: '44px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '2xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '500',
          lineHeight: '32px',
          fontSize: '33px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '200',
          lineHeight: '32px',
          fontSize: '33px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    xl: {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '300',
          lineHeight: '24px',
          fontSize: '22px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '500',
          lineHeight: '24px',
          fontSize: '22px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    l: {
      regular: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '500',
          lineHeight: '20px',
          fontSize: '16px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      bold: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '300',
          lineHeight: '20px',
          fontSize: '16px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    m: {
      regular: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '500',
          lineHeight: '16px',
          fontSize: '14px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      bold: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '400',
          lineHeight: '16px',
          fontSize: '14px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    s: {
      regular: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '500',
          lineHeight: '14px',
          fontSize: '11px',
          letterSpacing: '-2%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      bold: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '400',
          lineHeight: '14px',
          fontSize: '11px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    xs: {
      regular: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '500',
          lineHeight: '12px',
          fontSize: '8px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      bold: {
        value: {
          fontFamily: 'SB Sans Text Serif',
          fontWeight: '400',
          lineHeight: '12px',
          fontSize: '8px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
  },
  mono: {
    '8xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '500',
          lineHeight: '192px',
          fontSize: '220px',
          letterSpacing: '-8%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '200',
          lineHeight: '192px',
          fontSize: '220px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '7xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '500',
          lineHeight: '96px',
          fontSize: '110px',
          letterSpacing: '-6%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '200',
          lineHeight: '96px',
          fontSize: '110px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '6xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '500',
          lineHeight: '72px',
          fontSize: '88px',
          letterSpacing: '-6%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '200',
          lineHeight: '72px',
          fontSize: '88px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '5xl': {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '200',
          lineHeight: '56px',
          fontSize: '66px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '500',
          lineHeight: '56px',
          fontSize: '66px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '4xl': {
      regular: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '500',
          lineHeight: '48px',
          fontSize: '55px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      bold: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '200',
          lineHeight: '48px',
          fontSize: '55px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '3xl': {
      regular: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '500',
          lineHeight: '40px',
          fontSize: '44px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      bold: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '200',
          lineHeight: '40px',
          fontSize: '44px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    '2xl': {
      regular: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '500',
          lineHeight: '32px',
          fontSize: '33px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      bold: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '200',
          lineHeight: '32px',
          fontSize: '33px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    xl: {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '300',
          lineHeight: '24px',
          fontSize: '22px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '500',
          lineHeight: '24px',
          fontSize: '22px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    l: {
      regular: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '500',
          lineHeight: '20px',
          fontSize: '16px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      bold: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '300',
          lineHeight: '20px',
          fontSize: '16px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    m: {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '400',
          lineHeight: '16px',
          fontSize: '14px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '500',
          lineHeight: '16px',
          fontSize: '14px',
          letterSpacing: '-4%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    s: {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '500',
          lineHeight: '14px',
          fontSize: '11px',
          letterSpacing: '-2%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '400',
          lineHeight: '14px',
          fontSize: '11px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
    xs: {
      bold: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '500',
          lineHeight: '12px',
          fontSize: '8px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
      regular: {
        value: {
          fontFamily: 'SB Sans Text Mono',
          fontWeight: '400',
          lineHeight: '12px',
          fontSize: '8px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        type: 'typography',
      },
    },
  },
};
