/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GeneratedTooltipProps {
  size?: 'xs';
  borderRadius?: 'xl' | 'l' | 'm' | 's' | 'xs' | 'none';
  padding?: 'xl' | 'l' | 'm' | 's' | 'xs' | 'none';
}
