/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GeneratedPaperProps {
  shape?: 'square' | 'rounded';
  appearance?: 'solid' | 'solid-alt';
  color?:
    | 'transparent'
    | 'black'
    | 'white'
    | 'neutral-700'
    | 'neutral-600'
    | 'neutral-500'
    | 'neutral-400'
    | 'neutral-300'
    | 'neutral-200'
    | 'neutral-100'
    | 'accent-1-700'
    | 'accent-1-600'
    | 'accent-1-500'
    | 'accent-1-400'
    | 'accent-1-300'
    | 'accent-1-200'
    | 'accent-1-100'
    | 'accent-2-700'
    | 'accent-2-600'
    | 'accent-2-500'
    | 'accent-2-400'
    | 'accent-2-300'
    | 'accent-2-200'
    | 'accent-2-100'
    | 'informative-700'
    | 'informative-600'
    | 'informative-500'
    | 'informative-400'
    | 'informative-300'
    | 'informative-200'
    | 'informative-100'
    | 'positive-700'
    | 'positive-600'
    | 'positive-500'
    | 'positive-400'
    | 'positive-300'
    | 'positive-200'
    | 'positive-100'
    | 'attention-700'
    | 'attention-600'
    | 'attention-500'
    | 'attention-400'
    | 'attention-300'
    | 'attention-200'
    | 'attention-100'
    | 'negative-700'
    | 'negative-600'
    | 'negative-500'
    | 'negative-400'
    | 'negative-300'
    | 'negative-200'
    | 'negative-100';
}
